### PR TITLE
Flexible data location

### PR DESCRIPTION
**Pull request by khdlr**
This enables the flexible data location scheme mentioned in #6. It requires a new config parameter `data_root`, which can e.g. be set to
```yml
data_root: "data"
```
Note that it's also possible to specify an absolute path outside the project directory. This will make working with multiple branches/versions easier.

The subfolders then look like this:

Screenshot_20211129_112817

Currently, I'm not too happy with `data/data`, but kept it for lack of a better name. As it contains the intermediate tiled data between `setup_raw_data` and `preprocess_data`, maybe we could call it `data/tiles`?

### CODE REVIEW

**Comment by khdlr** [comment]
Rebased on current master

**Comment by khdlr** [comment]
Rebased on current master and dropped the commit from #21

**Comment by initze** [comment]
Will that screw old versions. Hence backward compatibility has to be set manually with adapting "data_root", correct?

I think it's a good implementation, I will merge soon and bump that to version 0.6 as kind of a major release

**Comment by khdlr** [comment]
Yes, this will indeed break old versions. In general, I believe this should be the way forward though. What are your thoughts on `data/data`? Would naming it `data/tiles` be fine?

**Comment by initze** [comment]
I think `data/tiles` would be even more appropriate

**Pull request merged**
